function out1 = T2(theta_9,d_10,theta_11,theta_12,theta_13)
%T2
%    OUT1 = T2(THETA_9,D_10,THETA_11,THETA_12,THETA_13)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    25-Feb-2018 17:04:13

t2 = cos(theta_9);
t3 = sin(theta_9);
t4 = t2.*6.123233995736766e-17;
out1 = reshape([t3.*(-6.123233995736766e-17)+t4,t3.*6.123233995736766e-17+t4,1.0,0.0,-t2-t3.*3.749399456654644e-33,t2.*3.749399456654644e-33-t3,6.123233995736766e-17,0.0,t3,-t2,6.123233995736766e-17,0.0,d_10.*t3,-d_10.*t2,d_10.*6.123233995736766e-17,1.0],[4,4]);
